version: "3"

includes:
  setup: tasks/Taskfile.setup.yaml
  kubectl: tasks/Taskfile.kubectl.yaml
  suicune:l0:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      PATH: landscapes/suicune/L0
  suicune:l1:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      PATH: landscapes/suicune/L1
  entei:l0:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      PATH: landscapes/entei/L0
  entei:l1:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      PATH: landscapes/entei/L1
  arceus:
    taskfile: tasks/Taskfile.landscape.yaml
    vars:
      PATH: landscapes/arceus

tasks:
  sync:
    desc: Sync static and secrets
    cmds:
      - ./scripts/local/sync.sh
