version: "3"

tasks:
  tf:
    dir: "{{.PATH}}"
    desc: "Initialize landscape"
    interactive: true
    cmds:
      - terraform {{.CLI_ARGS}}

  init:
    dir: "{{.PATH}}"
    desc: "Initialize landscape"
    interactive: true
    cmds:
      - terraform init {{.CLI_ARGS}}

  destroy:
    dir: "{{.PATH}}"
    desc: "Destroy landscape"
    interactive: true
    cmds:
      - terraform destroy {{.CLI_ARGS}}

  plan:
    dir: "{{.PATH}}"
    desc: "Plan landscape"
    interactive: true
    cmds:
      - terraform plan {{.CLI_ARGS}}

  apply:
    dir: "{{.PATH}}"
    desc: "Apply landscape"
    interactive: true
    cmds:
      - terraform apply {{.CLI_ARGS}}
